### PR TITLE
data.table conversion, machine generalization, data updates

### PR DESCRIPTION
**Pull request by Brandon-Whited**
Hi Liz, 
Here is the that update I promised you. Please let me know if you'd like to chat about what all I've done here. 
Many thanks!

### CODE REVIEW

**Review by eroten — COMMENTED** [review]
Great work! I made a few changes and summarized big changes here. Did I miss anything?

Update summary
- Use README.Rmd to generate README.md
- Remove old datasets floating around in data-raw
- All processing code (generally) refactored to use `{data.table}` over the tidyverse. Improves speed and stability.
- New object names
  - `hh` -> `household`
  - `veh` -> `vehicle`
  - `per` -> `person`
- `data/tbi19.rda` and `data/tbi21.rda` now contain `tbi19_rmPII` and `tbi21_rmPII`. To use the previous names, simply rename the objects as `tbi191 and `tbi21`
- Move most crosstab functions and extraneous work to `R/previous_code`
- Align 2019 and 2021 variables(?)

**Comment by Brandon-Whited** [comment]
Yes, you've captured it well. 

1. First and foremost, I'd like to make sure **_data-compile.R** and all the scripts it sources runs on your computer. Can you try it and let me know if you encounter any bugs? 
2. Some 2019 to 2021 alignment has been done. For example, '08-derive-var-trip-mode-group.R' explicitly derives variables that align. However, there is yet to be a fully inventory of fields that need to be aligned. 
3. I have a readme in the previous code folder detailing a vision for how to approach that folder. Let me know if you agree/disagree with it? 
4. If I'm being honest, the data.table conversion is mostly preference. If I was going to be the primary person maintaining this repo, I wanted it to be data.table. Give you're news, I might not be the primary maintainer in the future, so I dont want to totally claim its because of speed and stability improvements. 
5. I wasn't thinking about the renaming of tbi19_rmPII. I'm going to change it so that package users dont have to do that. 
6. We still need the _db_connect connection script, so I'm going to add it back. 

I'm going to make a handful of further refinements and push again.

**Comment by eroten** [comment]
@Brandon-Whited, sounds good! Honestly, I need to get into data.table because of the speed improvements. The time difference from dplyr is noticeable on my end.

For another time, I can help with variable aligning. I've done some of that work with the EV report, but it would be nice to have it centralized here.

**Review by eroten — APPROVED** [review]
Great work, Brandon! Thank you!

**Pull request merged**
